<?php use App\Framework\UserSession; ?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--title>Mon blog! <?=isset($pageTitle)?$pageTitle:'';?></title-->
    <title>Mon blog! <?=$pageTitle??'';?></title>
    <link rel="stylesheet" href="<?=asset('css/style.css');?>">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <h1><a href="<?=buildUrl('homepage');?>">Bienvenue sur mon blog !!</a></h1>
        <nav class="navbar">
            <!-- Menu en mode déonnecté -->
        <?php if (!UserSession::isAuthenticated()): ?>
            <a class="btn" href="<?=buildUrl('login');?>"><i class="fas fa-sign-in-alt"></i> Connexion</a>
            <a class="btn" href="<?=buildUrl('signup');?>"><i class="fas fa-user-plus"></i> Créer un compte</a>
        <?php else: ?>
            <!-- Menu en mode connecté -->
            <span><i class="fas fa-user"></i></i> <?=UserSession::getFirstname() . ' ' . UserSession::getLastname();?></span>
            <a class="btn" href="<?=buildUrl('logout');?>"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            <a class="btn" href="<?=buildUrl('admin');?>"><i class="fas fa-cogs"></i> Administration</a>
        <?php endif; ?>
        </nav>
    </header>
    <main>
        <aside>
            <?php if (App\Framework\FlashBag::hasMessages('error')):?>
                <?php foreach (App\Framework\FlashBag::fetchMessages('error') as $error):?>
                    <p class="message error-message"><?=htmlspecialchars($error);?></p>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php if (App\Framework\FlashBag::hasMessages('success')):?>
                <?php foreach (App\Framework\FlashBag::fetchMessages('success') as $message):?>
                    <p class="message success-message"><?=htmlspecialchars($message);?></p>
                <?php endforeach; ?>
            <?php endif; ?>
        </aside>

        <?php include TEMPLATE_DIR . '/' . $template . '.phtml'; ?>
    </main>
    <footer></footer>
</body>
</html>