<!-- Template spécifique à la page d'accueil -->

<?php if (isset($category)): ?>
    <h2>Articles de la catégorie "<?=$category['label'];?>"</h2>
<?php else: ?>
    <h2>Les derniers articles</h2>
<?php endif; ?>

<?php foreach ($articles as $article): ?>
    <article>
        <h3><?=htmlspecialchars($article['title']);?></h3>
        <a href="<?=buildUrl('homepage', ['category' => $article['category_id']])?>" class="badge"><?=$article['category_label'];?></a>
        <p>Date de création : <?=(new DateTimeImmutable($article['created_at']))->format('d/m/Y');?></p>
        <div><?=htmlspecialchars(mb_substr($article['content'],0,150));?></div>
        <a href="<?=buildUrl('article', ['id' => intval($article['article_id'])]);?>">Lire la suite</a>
    </article>
<?php endforeach; ?>
    