<form class="signup-form" action="<?=buildUrl('login');?>" method="POST">
    <fieldset>
        <legend>Connexion</legend>
        <div>
            <label for="email">Email</label>
            <input type="email" name="email" id="email">
        </div>
        <div>
            <label for="password">Mot de passe</label>
            <input type="password" name="password" id="password">
        </div>
    </fieldset>
    <input type="submit" value="Enregistrer">
</form>