<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/style.css">
    <title>Document</title>
</head>
<body>

    <form class = "Form" id="form-generate"  action="index.php" method="POST">
        <input type="hidden" name="action" value="generate">
        <div>
            <label for="size-select">Taille</label>
            <select name="size" id="size-select">
                <?php for ($i =1 ; $i<=10; $i++):?>
                    <option id = 'selected-size' <?=$i == $size? 'selected' : '';?> value="<?=$i?>"><?=$i?></option>
                <?php endfor; ?>
            </select>
        </div>
        <div>
            <label for="color-select">Nombre de Couleurs</label>
            <select name="color" id="color-select">
                    <?php for ($i =1 ; $i<=10; $i++):?>
                        <option id ='selected-nbColor' <?=$i == $nbColor? 'selected' : '';?> value="<?=$i?>"><?=$i?></option>
                    <?php endfor; ?>           
            </select>
        </div>
        <div>
            <input type="radio" id="vertical" name="symetrie" value="vertical" <?=$symetry == 'vertical'? 'checked':''; ?>>
            <label for="vertical">Symétrie Vertical</label>
            <input type="radio" id="horizontal" name="symetrie" value="horizontal"<?=$symetry == 'horizontal'? 'checked':''; ?>>
            <label for="horizontal">Symétrie Horizontale</label>
            <input type="radio" id="horizontal" name="symetrie" value="diagonale"<?=$symetry == 'diagonale'? 'checked':''; ?>>
            <label for="horizontal">Symétrie Diagonale</label>
        </div>
                
        <button class="submit-button" id="submit-button-generate" type="submit">Generer</button>
    </form>
    <div id='avatar-container'><?php echo $svg?></div>
    <form id="save-form" action="index.php" method="POST">
        <input id ="enregister-svg" type='hidden' name ="svg" value="<?= htmlspecialchars($svg) ?>">
        <input type="submit" value="Enregister">
        <input type="hidden" name ="action" value='save'>
        <input id="enregistrer-size" type="hidden" name="size" value="<?=$size;?>">
        <input id="enregistrer-nbColor" type="hidden" name="color" value="<?=$nbColor;?>">
    </form>
    <form action="index.php" method="POST">
        <input id="ddl-svg" type='hidden' name ="svg" value="<?= htmlspecialchars($svg) ?>">
        <input type="submit" value="Telecharger">
        <input type="hidden" name ="action" value='download'>
    </form>
<script src="/js/app.js"></script>    
</body>
</html>