<section>
    <h2>Rédiger un article</h2>

    <form action="<?=buildUrl('admin_article_edit', ['article_id' => $articleId]);?>" method="post">
        <fieldset>
            <div>
                <label for="title">Titre</label>
                <input type="text" id="title" name="title" value="<?=$title?>" required>
            </div>
            <div>
                <label for="content">Contenu</label>
                <textarea id="content" name="content" required><?=$content?></textarea>
            </div>
            <div>
                <label for="category">Catégorie</label>
                <select id="category" name="category" required>
                    <?php foreach ($categories as $category): ?>
                        <?php $selected = isset($selectedCategory) && $category['id'] == $selectedCategory ? 'selected' : ''; ?>
                        <option <?=$selected?> value="<?=$category['id'];?>"><?=$category['label'];?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </fieldset>
        <input type="submit" value="Valider">
    </form>
</section>