<main class = PageSignup>
    <form class="Signup-form Form" action="<?=buildUrl('signup');?>" method="POST">
        <fieldset class="Form">
            <h2>Créez votre compte</h2>
            <div class="Form-field">
                <label class="Form-field-label" for="firstname">Prénom</label>
                <input class="Form-field-content" type="text" name="firstname" id="firstname" value="<?=$firstname;?>">
            </div>
            <div class="Form-field">
                <label class="Form-field-label" for="lastname">Nom</label>
                <input class="Form-field-content" type="text" name="lastname" id="lastname" value="<?=$lastname;?>">
            </div>
            <div class="Form-field">

                <label class="Form-field-label" for="email">Email</label>
               
                <input class="Form-field-content" type="email" name="email" id="email" value="<?=$email;?>">
                
            </div>
            <div class="Form-field">
                <label class="Form-field-label" for="password">Mot de passe</label>
                
                <input class="Form-field-content" type="password" name="password" id="password">
                
            </div>
            <input class ="Form-submit" type="submit" value="Enregistrer">
        </fieldset>
        
    </form>
</main>